// Logins
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Signups
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

// Update
export const UPDATE_START = 'UPDATE_START';
export const UPDATE_FAILED = 'UPDATE_FAILED';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';

// Password Change
export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

// Auth extra
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

// FriendShips
export const GET_FRIENDS = 'GET_FRIENDS';
export const START_GET_FRIEND = 'START_GET_FRIEND';
export const GET_FRIEND_SUCCESS = 'GET_FRIEND_SUCCESS';
export const GET_FRIEND_FAILED = 'GET_FRIEND_FAILED';
export const START_FOLLOW_TOGGLE = 'START_FOLLOW_TOGGLE';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAILED = 'FOLLOW_FAILED';
// Posts
export const UPDATE_POSTS = 'UPDATE_POSTS';
// Post Add
export const START_POSTING = 'START_POSTING';
export const POSTING_FAILED = 'POSTING_FAILED';
export const POSTING_SUCCESS = 'POSTING_SUCCESS';

// Likes
export const START_LIKE = 'START_LIKE';
export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const LIKE_FAILED = 'LIKE_FAILED';

// Delete
export const START_DELETE_POST = 'START_DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';

// Searching
export const START_SEARCH = 'START_SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';

// Snackbar
export const SET_SNACKBAR = 'SET_SNACKBAR';
export const CLEAR_SNACKBAR = 'CLEAR_SNACKBAR';

// Get User
export const START_GET_USER = 'START_GET_USER';
export const GET_USER_FAILED = 'GET_USER_FAILED';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
